# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourismPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='観光ポイント名')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
    ]
