# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miuride_app', '0002_tourismcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='a9030a50-2e98-4a0c-8bba-5f3ae71361df', max_length=36)),
            ],
        ),
    ]
