# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miuride_app', '0003_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='uuid',
            name='uuid',
            field=models.CharField(default='3335a9f5-876c-465a-b4c5-0a8f49f9e79e', max_length=36),
        ),
        migrations.AddField(
            model_name='location',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miuride_app.UUID'),
        ),
    ]
