# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miuride_app', '0004_auto_20170319_2143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Breadcrumb',
        ),
        migrations.AlterField(
            model_name='uuid',
            name='uuid',
            field=models.CharField(default='dafee9c2-54fe-4593-8ca6-3186dd171277', max_length=36),
        ),
    ]
